import type { Metadata } from "next";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";

import "@mantine/core/styles.css";
import { RootStyleRegistry } from "./EmotionRootStyleRegistry";
import { emotionTransform, MantineEmotionProvider } from "@mantine/emotion";
import QueryProvider from "./QueryProvider";
import UserProvider from "./UserProvider";

export const metadata: Metadata = {
  title: {
    default: "FindFlow",
    template: "%s | FindFlow",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ColorSchemeScript />
      </head>

      <body>
        <QueryProvider>
          <RootStyleRegistry>
            <MantineEmotionProvider>
              <UserProvider>
                <MantineProvider stylesTransform={emotionTransform}>{children}</MantineProvider>
              </UserProvider>
            </MantineEmotionProvider>
          </RootStyleRegistry>
        </QueryProvider>
      </body>
    </html>
  );
}
