import type { Metadata } from "next";
import "./globals.css";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";

import '@mantine/core/styles.css';
import { RootStyleRegistry } from "./EmotionRootStyleRegistry";
import {
  emotionTransform,
  MantineEmotionProvider,
} from '@mantine/emotion';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>

      <head>
        <ColorSchemeScript />
      </head>

        <body>
        <RootStyleRegistry>
          <MantineEmotionProvider>
            <MantineProvider stylesTransform={emotionTransform}> 
              {children}
            </MantineProvider>
          </MantineEmotionProvider>
        </RootStyleRegistry>
        </body>
    </html>
  );
}
